version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: miniestacion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tycgis
    ports:
      - "5432:5432"
