version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=miniestacion
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tycgis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: