version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: miniestacion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tycgis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
