version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tycgis
      POSTGRES_DB: miniestacion
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:tycgis@db:5432/miniestacion
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: